"""add referrer_id to users

Revision ID: 0b17e46e8fb4
Revises: d2d0ead70020
Create Date: 2025-06-09 05:50:52.734004

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0b17e46e8fb4'
down_revision: Union[str, None] = 'd2d0ead70020'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('referrer_id', sa.BIGINT(), nullable=True))
    op.add_column('users', sa.Column('referral_count', sa.BIGINT(), server_default=sa.text('0'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'referral_count')
    op.drop_column('users', 'referrer_id')
    # ### end Alembic commands ###
