"""add tests

Revision ID: 35c6166b2db0
Revises: 9abced462d9e
Create Date: 2025-03-29 16:37:55.344334

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '35c6166b2db0'
down_revision: Union[str, None] = '9abced462d9e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tests',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BIGINT(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('is_show_correct_count', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('is_show_incorrects', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('is_show_answers', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('is_finished', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('finished_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('submissions',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('text', sa.String(length=1024), nullable=True),
    sa.Column('correct_count', sa.Integer(), nullable=False),
    sa.Column('incorrect_count', sa.Integer(), nullable=False),
    sa.Column('score', sa.Float(precision=2), nullable=False),
    sa.Column('user_id', sa.BIGINT(), nullable=False),
    sa.Column('test_id', sa.BIGINT(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['test_id'], ['tests.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('test_answers',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(length=128), nullable=True),
    sa.Column('type', sa.Integer(), nullable=False),
    sa.Column('score', sa.Float(precision=2), nullable=False),
    sa.Column('test_id', sa.BIGINT(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['test_id'], ['tests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('submitted_answers',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('text', sa.String(length=128), nullable=True),
    sa.Column('is_correct', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('score', sa.Float(precision=2), nullable=False),
    sa.Column('submission_id', sa.BIGINT(), nullable=False),
    sa.Column('test_answer_id', sa.BIGINT(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['submission_id'], ['submissions.id'], ),
    sa.ForeignKeyConstraint(['test_answer_id'], ['test_answers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('submitted_answers')
    op.drop_table('test_answers')
    op.drop_table('submissions')
    op.drop_table('tests')
    # ### end Alembic commands ###
